apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: sandia-study-cluster
  labels:
    cluster: cloud
    location: eks
    cost-tier: paid
spec:
  # 2-node cluster matching our EKS node count
  size: 2
  
  # Number of parallel tasks
  tasks: 2
  
  # Flux container configuration
  containers:
    - image: ghcr.io/flux-framework/flux-restful-api:latest
      workingDir: /home/flux
      # Mount EFS for persistent storage (benchmarks, results)
      volumes:
        data:
          path: /data
          claimName: flux-pvc  # Logging for debugging
  flux:
    logLevel: 7
